### ISSUE TITLE
should simplify how to get the latest docker-compose release version

### ISSUE THREAD

**Issue by hoatle** [teracyhq/dev#374]
use this:

```
curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d\" -f4
```

instead of:

```
curl -s https://api.github.com/repos/docker/compose/releases/latest | sed 's/[{}]//g' | awk -v k=text '{n=split($0,a,\",\"); for (i=1; i<=n; i++) print a[i]}' | sed 's/\"\:\"/\|/g' | sed 's/[\,]/ /g' | sed 's/\"//g' | grep -w 'tag_name' | awk '{print $2}' | awk 1 ORS=''
```

from: https://github.com/teracyhq/dev/blob/develop/main-cookbooks/teracy-dev/recipes/docker.rb#L40

**Comment by hoatle** [comment]
@phuonglm @datphan: @duc4nh and I got this error:

```
==> default: ================================================================================
==> default: Recipe Compile Error in /var/chef/cache/cookbooks/teracy-dev/recipes/default.rb
==> default: ================================================================================
==> default: 
==> default: Mixlib::ShellOut::ShellCommandFailed
==> default: ------------------------------------
==> default: Expected process to exit with [0], but received '2'
==> default: ---- Begin output of curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d" -f4 ----
==> default: STDOUT: 
==> default: STDERR: sh: 1: Syntax error: Unterminated quoted string
==> default: ---- End output of curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d" -f4 ----
==> default: Ran curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d" -f4 returned 2
==> default: 
==> default: Cookbook Trace:
==> default: ---------------
==> default:   /var/chef/cache/cookbooks/teracy-dev/recipes/docker.rb:44:in `get_docker_compose_release'
==> default:   /var/chef/cache/cookbooks/teracy-dev/recipes/docker.rb:53:in `get_docker_compose_autocomplete_url'
==> default:   /var/chef/cache/cookbooks/teracy-dev/recipes/docker.rb:126:in `from_file'
==> default:   /var/chef/cache/cookbooks/teracy-dev/recipes/default.rb:37:in `from_file'
==> default: 
==> default: Relevant File Content:
==> default: ----------------------
==> default: /var/chef/cache/cookbooks/teracy-dev/recipes/docker.rb:
==> default: 
==> default:  37:      release = node['docker_compose']['release']
==> default:  38:  
==> default:  39:      if release.empty?
==> default:  40:          result = Mixlib::ShellOut.new("curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d\" -f4")
==> default:  41:  
==> default:  42:          result.run_command
==> default:  43:  
==> default:  44>>         result.error!
==> default:  45:  
==> default:  46:          node.override['docker_compose']['release'] = release = result.stdout
==> default:  47:      end
==> default:  48:  
==> default:  49:      release
==> default:  50:  end
==> default:  51:  
==> default:  52:  def get_docker_compose_autocomplete_url
==> default:  53:      "https://raw.githubusercontent.com/docker/compose/#{get_docker_compose_release}/contrib/completion/bash/docker-compose"
==> default: 
==> default: System Info:
==> default: ------------
==> default: chef_version=13.1.31
==> default: platform=ubuntu
==> default: platform_version=16.04
==> default: ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
==> default: program_name=chef-solo worker: ppid=2388;start=14:15:51;
==> default: executable=/opt/chef/bin/chef-solo
==> default: 
==> default: 
==> default: Running handlers:
==> default: [2017-07-26T14:16:00+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2017-07-26T14:16:00+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 0 resources updated in 09 seconds
==> default: [2017-07-26T14:16:00+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2017-07-26T14:16:00+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2017-07-26T14:16:00+00:00] ERROR: Expected process to exit with [0], but received '2'
==> default: ---- Begin output of curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d" -f4 ----
==> default: STDOUT: 
==> default: STDERR: sh: 1: Syntax error: Unterminated quoted string
==> default: ---- End output of curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d" -f4 ----
==> default: Ran curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d" -f4 returned 2
==> default: [2017-07-26T14:16:00+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
==> default: The previous process exited with exit code 1.
```

**Comment by hoatle** [comment]
@phuonglm please verify and get this closed soon.

**Comment by phuonglm** [comment]
verify and it's fixed
