### ISSUE TITLE
gitsynch: tag sync did not work properly, vagrant was reloaded repeatedly

### ISSUE THREAD

**Issue by hoatle** [teracyhq/dev#453]
Follow this to reproduce the bug: https://github.com/teracyhq-incubator/teracy-dev-entry-k8s#how-to-use

Note: configure to use teracy-dev v0.6.0-a1 (tag version) https://github.com/teracyhq-incubator/teracy-dev-entry-k8s/commit/ddd3a8218ad9142590276060a3d88dcbdf6a2875#diff-4ef5de0b4cef20023b8bd5e2031938bfR5

expected:

- $ vagrant status or $ vagrant up should work

Actual:

vagrant was reloaded repeatedly

**Comment by hoatle** [comment]
actually, gitsynch is super buggy:

```
macbook-pro:k8s-dev hoatle$ vagrant status
HEAD is now at 5759ae4... Merge pull request #6 from hoatle/tasks/#5-v0.1.0-release
HEAD is now at 0080154... Merge pull request #17 from hoatle/tasks/#16-v0.1.0-release
error: pathspec 'tags/branch' did not match any file(s) known to git.
[TeracyDev::Loader][INFO]: reloading...	/Users/hoatle/test-teracy-dev/k8s-dev/lib/teracy-dev.rb:31:in `<module:TeracyDev>'

HEAD is now at 5759ae4... Merge pull request #6 from hoatle/tasks/#5-v0.1.0-release
HEAD is now at 0080154... Merge pull request #17 from hoatle/tasks/#16-v0.1.0-release
error: pathspec 'tags/branch' did not match any file(s) known to git.
[TeracyDev::Loader][INFO]: reloading...	/Users/hoatle/test-teracy-dev/k8s-dev/lib/teracy-dev.rb:31:in `<module:TeracyDev>'

HEAD is now at 5759ae4... Merge pull request #6 from hoatle/tasks/#5-v0.1.0-release
HEAD is now at 0080154... Merge pull request #17 from hoatle/tasks/#16-v0.1.0-release
error: pathspec 'tags/branch' did not match any file(s) known to git.
[TeracyDev::Loader][INFO]: reloading...	/Users/hoatle/test-teracy-dev/k8s-dev/lib/teracy-dev.rb:31:in `<module:TeracyDev>'

HEAD is now at 5759ae4... Merge pull request #6 from hoatle/tasks/#5-v0.1.0-release
HEAD is now at 0080154... Merge pull request #17 from hoatle/tasks/#16-v0.1.0-release
error: pathspec 'tags/branch' did not match any file(s) known to git.
[TeracyDev::Loader][INFO]: reloading...	/Users/hoatle/test-teracy-dev/k8s-dev/lib/teracy-dev.rb:31:in `<module:TeracyDev>'

HEAD is now at 5759ae4... Merge pull request #6 from hoatle/tasks/#5-v0.1.0-release
HEAD is now at 0080154... Merge pull request #17 from hoatle/tasks/#16-v0.1.0-release
error: pathspec 'tags/branch' did not match any file(s) known to git.
[TeracyDev::Loader][INFO]: reloading...	/Users/hoatle/test-teracy-dev/k8s-dev/lib/teracy-dev.rb:31:in `<module:TeracyDev>'

HEAD is now at 5759ae4... Merge pull request #6 from hoatle/tasks/#5-v0.1.0-release
HEAD is now at 0080154... Merge pull request #17 from hoatle/tasks/#16-v0.1.0-release
```
