### ISSUE TITLE
something wrong with the plugin installation when no plugin is installed

### ISSUE THREAD

**Issue by hoatle** [teracyhq/dev#486]
```hoatle~/k8s-dev$ vagrant status
[Plugin][INFO]: installing plugin: {"_id"=>"essential-0", "name"=>"vagrant-hostmanager", "version"=>"", "state"=>"installed", "config_key"=>"hostmanager", "enabled"=>true, "options"=>{"enabled"=>true, "manage_host"=>true, "manage_guest"=>true}}
/home/hoatle/k8s-dev/lib/teracy-dev/plugin.rb:19:in `block in sync'

[Plugin][INFO]: installing plugin: {"_id"=>"essential-0", "name"=>"vagrant-hostmanager", "version"=>"", "state"=>"installed", "config_key"=>"hostmanager", "enabled"=>true, "options"=>{"enabled"=>true, "manage_host"=>true, "manage_guest"=>true}}
/home/hoatle/k8s-dev/lib/teracy-dev/plugin.rb:19:in `block in sync'

Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Unable to resolve dependency: user requested 'vagrant-hostmanager (> 0)'
hoatle~/k8s-dev$ vagrant plugin install vagrant-hostmanager
Installing the 'vagrant-hostmanager' plugin. This can take a few minutes...
Fetching: vagrant-hostmanager-1.8.9.gem (100%)
Installed the plugin 'vagrant-hostmanager (1.8.9)'!
hoatle~/k8s-dev$ vagrant plugin uninstall vagrant-hostmanager
Uninstalling the 'vagrant-hostmanager' plugin...
Successfully uninstalled vagrant-hostmanager-1.8.9
hoatle~/k8s-dev$ vagrant status
[Plugin][INFO]: installing plugin: {"_id"=>"essential-0", "name"=>"vagrant-hostmanager", "version"=>"", "state"=>"installed", "config_key"=>"hostmanager", "enabled"=>true, "options"=>{"enabled"=>true, "manage_host"=>true, "manage_guest"=>true}}
/home/hoatle/k8s-dev/lib/teracy-dev/plugin.rb:19:in `block in sync'

[Plugin][INFO]: installing plugin: {"_id"=>"essential-0", "name"=>"vagrant-hostmanager", "version"=>"", "state"=>"installed", "config_key"=>"hostmanager", "enabled"=>true, "options"=>{"enabled"=>true, "manage_host"=>true, "manage_guest"=>true}}
/home/hoatle/k8s-dev/lib/teracy-dev/plugin.rb:19:in `block in sync'

Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Unable to resolve dependency: user requested 'vagrant-hostmanager (> 0)'
```

It's expected that vagrant plugin config should work, but it's broken now. However, `$ vagrant plugin install` works, this is weird.

**Comment by hoatle** [comment]
the bug happened on both teracy-dev v0.6.0-a4 and the current develop branch, on both vagrant v2.1.0 and v2.1.5, on Ubuntu and macOS

**Comment by hoatle** [comment]
we need to make sure that `installed` and `uninstalled` state config works great.

**Comment by hoatle** [comment]
ref: https://github.com/hashicorp/vagrant/blob/master/plugins/commands/plugin/action/install_gem.rb#L30

**Comment by hoatle** [comment]
make sure no plugin is installed

**Comment by hoatle** [comment]
```
hoatle~/k8s-dev$ vagrant plugin list
No plugins installed.
hoatle~/k8s-dev$ vagrant status
[TeracyDev::Plugin][INFO]: installing plugin: {"_id"=>"essential-0", "name"=>"vagrant-hostmanager", "version"=>"", "state"=>"installed", "config_key"=>"hostmanager", "enabled"=>true, "options"=>{"enabled"=>true, "manage_host"=>true, "manage_guest"=>true}}
/home/hoatle/k8s-dev/lib/teracy-dev/plugin.rb:19:in `block in sync'

[TeracyDev::Plugin][INFO]: installing plugin: {"_id"=>"essential-0", "name"=>"vagrant-hostmanager", "version"=>"", "state"=>"installed", "config_key"=>"hostmanager", "enabled"=>true, "options"=>{"enabled"=>true, "manage_host"=>true, "manage_guest"=>true}}
/home/hoatle/k8s-dev/lib/teracy-dev/plugin.rb:19:in `block in sync'

Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Unable to resolve dependency: user requested 'vagrant-hostmanager (> 0)'
hoatle~/k8s-dev$ vagrant plugin install vagrant-gatling-rsync
Installing the 'vagrant-gatling-rsync' plugin. This can take a few minutes...
Fetching: vagrant-gatling-rsync-0.9.0.gem (100%)
Installed the plugin 'vagrant-gatling-rsync (0.9.0)'!
hoatle~/k8s-dev$ vagrant status
[TeracyDev::Plugin][INFO]: installing plugin: {"_id"=>"essential-0", "name"=>"vagrant-hostmanager", "version"=>"", "state"=>"installed", "config_key"=>"hostmanager", "enabled"=>true, "options"=>{"enabled"=>true, "manage_host"=>true, "manage_guest"=>true}}
/home/hoatle/k8s-dev/lib/teracy-dev/plugin.rb:19:in `block in sync'

Fetching: vagrant-hostmanager-1.8.9.gem (100%)
[TeracyDev::Plugin][INFO]: reloading...
/home/hoatle/k8s-dev/lib/teracy-dev/plugin.rb:32:in `sync'

Current machine states:

k8s-01                    running (virtualbox)

The VM is running. To stop this VM, you can run `vagrant halt` to
shut it down forcefully, or you can run `vagrant suspend` to simply
suspend the virtual machine. In either case, to restart it again,
simply run `vagrant up`.
hoatle~/k8s-dev$ vagrant plugin list
vagrant-gatling-rsync (0.9.0)
vagrant-hostmanager (1.8.9)
```

**Comment by hoatle** [comment]
verified, closed.
