### ISSUE TITLE
failed to sync teracy-dev-entry

### ISSUE THREAD

**Issue by hoatle** [teracyhq/dev#523]
use this: https://github.com/teracyhq-incubator/teracy-dev-entry-k8s

it should work with teracy-dev v0.6.0-a4 and v0.6.0-a5

```
hoatle~/k8s-dev$ vagrant status
remote: Enumerating objects: 54, done.
remote: Counting objects: 100% (54/54), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 116 (delta 47), reused 52 (delta 47), pack-reused 62
Receiving objects: 100% (116/116), 18.35 KiB | 0 bytes/s, done.
Resolving deltas: 100% (60/60), completed with 11 local objects.
From https://github.com/teracyhq/dev
   e90308d..0f8a7db  develop    -> origin/develop
Already on 'develop'
[TeracyDev::Loader][INFO]: reloading...
/home/hoatle/k8s-dev/lib/teracy-dev/loader.rb:62:in `sync_teracy_dev'

[TeracyDev::Location::GitSynch][WARN]: Deprecated string value at location.git of location: {"git"=>"https://github.com/teracyhq/dev.git", "sync"=>true, "branch"=>"develop", "path"=>"/home/hoatle/k8s-dev/lib/.."}, please use location.git.remote.origin instead
/home/hoatle/k8s-dev/lib/teracy-dev/location/git_synch.rb:26:in `sync'

[TeracyDev::Location::GitSynch][WARN]: ["branch"] of location setting has been deprecated at location: {"git"=>"https://github.com/teracyhq/dev.git", "sync"=>true, "branch"=>"develop", "path"=>"/home/hoatle/k8s-dev/lib/.."}, please use location['git'][<branch|tag|ref|dir>] instead
/home/hoatle/k8s-dev/lib/teracy-dev/location/git_synch.rb:38:in `sync'

[TeracyDev::Location::GitSynch][WARN]: ["branch"] of location setting has been deprecated at location: {"git"=>{"remote"=>{"origin"=>nil}, "branch"=>nil, "tag"=>nil, "ref"=>nil, "dir"=>"teracy-dev-entry"}, "sync"=>true, "branch"=>"develop", "lookup_path"=>"/home/hoatle/k8s-dev/lib/../workspace", "path"=>"/home/hoatle/k8s-dev/lib/../workspace/teracy-dev-entry"}, please use location['git'][<branch|tag|ref|dir>] instead
/home/hoatle/k8s-dev/lib/teracy-dev/location/git_synch.rb:38:in `sync'

[TeracyDev::Location::GitSynch][ERROR]: git.remote.origin is required for /home/hoatle/k8s-dev/lib/../workspace/teracy-dev-entry
/home/hoatle/k8s-dev/lib/teracy-dev/location/git_synch.rb:48:in `sync'
```

bug from https://github.com/teracyhq/dev/issues/502

**Comment by hoatle** [comment]
bug from this: https://github.com/teracyhq/dev/blob/develop/lib/teracy-dev/loader.rb#L68
