### ISSUE TITLE
update docs for "win32/registry.rb:185:in `encode!': code converter not found (UTF-16LE to Windows-1258) (Encoding::ConverterNotFoundError)" error on Windows

### ISSUE THREAD

**Issue by hoavt** [teracyhq/dev#544]
```Administrator@CBS85CFXNI4FWJ5 /cygdrive/f/teracy/iorad-dev
$ TERACY_DEV_ENTRY_LOCATION_GIT_REMOTE_ORIGIN=git@github.com:iorad/teracy-dev-entry.git \
>   TERACY_DEV_ENTRY_LOCATION_GIT_BRANCH=develop TERACY_DEV_ENTRY_LOCATION_SYNC=true \
>   vagrant status
[TeracyDev::Location::GitSynch][INFO]: cd F:/teracy/iorad-dev/lib/../workspace && git clone git@github.com:iorad/teracy-dev-entry.git teracy-dev-entry
F:/teracy/iorad-dev/lib/teracy-dev/location/git_synch.rb:93:in `block in sync'
Cloning into 'teracy-dev-entry'...
remote: Enumerating objects: 48, done.
remote: Counting objects: 100% (48/48), done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 48 (delta 22), reused 39 (delta 13), pack-reused 0
Receiving objects: 100% (48/48), 8.06 KiB | 1.01 MiB/s, done.
Resolving deltas: 100% (22/22), done.
[TeracyDev::Location::GitSynch][INFO]: cd F:/teracy/iorad-dev/lib/../workspace/teracy-dev-entry && git checkout develop
F:/teracy/iorad-dev/lib/teracy-dev/location/git_synch.rb:98:in `block in sync'
Already on 'develop'
Your branch is up to date with 'origin/develop'.
[TeracyDev::Loader][INFO]: reloading...
F:/teracy/iorad-dev/lib/teracy-dev/loader.rb:130:in `sync_teracy_dev_entry'
[TeracyDev::Location::GitSynch][WARN]: `F:/teracy/iorad-dev/lib/..` has untracked changes, auto update is aborted!
 On branch develop
Your branch is up to date with 'origin/develop'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        dev-setup/
nothing added to commit but untracked files present (use "git add" to track)
F:/teracy/iorad-dev/lib/teracy-dev/location/git_synch.rb:71:in `block in sync'
[TeracyDev::Location::GitSynch][INFO]: cd F:/teracy/iorad-dev/lib/../extensions && git clone https://github.com/teracyhq-incubator/teracy-dev-certs.git
F:/teracy/iorad-dev/lib/teracy-dev/location/git_synch.rb:93:in `block in sync'
Cloning into 'teracy-dev-certs'...
remote: Enumerating objects: 63, done.
remote: Counting objects: 100% (63/63), done.
remote: Compressing objects: 100% (39/39), done.
remote: Total 63 (delta 22), reused 53 (delta 12), pack-reused 0
Unpacking objects: 100% (63/63), done.
[TeracyDev::Location::GitSynch][INFO]: cd F:/teracy/iorad-dev/lib/../extensions/teracy-dev-certs && git checkout develop
F:/teracy/iorad-dev/lib/teracy-dev/location/git_synch.rb:98:in `block in sync'
Already on 'develop'
Your branch is up to date with 'origin/develop'.
[TeracyDev::Location::GitSynch][INFO]: cd F:/teracy/iorad-dev/lib/../extensions && git clone git@github.com:iorad/teracy-dev-iorad-common.git
F:/teracy/iorad-dev/lib/teracy-dev/location/git_synch.rb:93:in `block in sync'
Cloning into 'teracy-dev-iorad-common'...
remote: Enumerating objects: 139, done.
remote: Counting objects: 100% (139/139), done.
remote: Compressing objects: 100% (82/82), done.
remote: Total 139 (delta 40), reused 131 (delta 33), pack-reused 0
Receiving objects: 100% (139/139), 30.62 KiB | 130.00 KiB/s, done.
Resolving deltas: 100% (40/40), done.
[TeracyDev::Location::GitSynch][INFO]: cd F:/teracy/iorad-dev/lib/../extensions/teracy-dev-iorad-common && git checkout develop
F:/teracy/iorad-dev/lib/teracy-dev/location/git_synch.rb:98:in `block in sync'
Already on 'develop'
Your branch is up to date with 'origin/develop'.
[TeracyDev::Plugin][INFO]: installing plugin: {"_id"=>"essential-0", "name"=>"vagrant-hostmanager", "version"=>"", "state"=>"installed", "config_key"=>"hostmanager", "enabled"=>true, "options"=>{"enabled"=>true, "manage_host"=>true, "manage_guest"=>true}, "sources"=>["https://rubygems.org/", "https://gems.hashicorp.com/"]}
F:/teracy/iorad-dev/lib/teracy-dev/plugin.rb:35:in `block in sync'
C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:185:in `encode!': code converter not found (UTF-16LE to Windows-1258) (Encoding::ConverterNotFoundError)
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:185:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:250:in `exception'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:250:in `raise'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:250:in `check'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:320:in `QueryValue'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:644:in `read'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/resolv.rb:67:in `read_s'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/resolv.rb:101:in `block in get_info'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:435:in `open'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:542:in `open'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/resolv.rb:91:in `get_info'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/resolv.rb:21:in `get_resolv_info'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:1002:in `default_config_hash'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:1019:in `block in lazy_initialize'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:1012:in `synchronize'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:1012:in `lazy_initialize'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:358:in `block in lazy_initialize'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:356:in `synchronize'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:356:in `lazy_initialize'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:516:in `fetch_resource'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:510:in `each_resource'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:491:in `getresource'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/remote_fetcher.rb:105:in `api_endpoint'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/source.rb:47:in `api_uri'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/source.rb:183:in `load_specs'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/bundler.rb:424:in `block in validate_configured_sources!'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/source_list.rb:98:in `each'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/source_list.rb:98:in `each_source'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/bundler.rb:422:in `validate_configured_sources!'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/bundler.rb:330:in `internal_install'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/bundler.rb:128:in `install'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/plugin/manager.rb:138:in `block in install_plugin'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/plugin/manager.rb:148:in `install_plugin'
        from F:/teracy/iorad-dev/lib/teracy-dev/plugin.rb:36:in `block in sync'
        from F:/teracy/iorad-dev/lib/teracy-dev/plugin.rb:16:in `each'
        from F:/teracy/iorad-dev/lib/teracy-dev/plugin.rb:16:in `sync'
        from F:/teracy/iorad-dev/extensions/teracy-dev-core/lib/teracy-dev-core/config/plugins.rb:17:in `configure'
        from F:/teracy/iorad-dev/lib/teracy-dev/config/manager.rb:40:in `block in configure'
        from F:/teracy/iorad-dev/lib/teracy-dev/config/manager.rb:38:in `each'
        from F:/teracy/iorad-dev/lib/teracy-dev/config/manager.rb:38:in `configure'
        from F:/teracy/iorad-dev/lib/teracy-dev/loader.rb:185:in `configure'
        from F:/teracy/iorad-dev/lib/teracy-dev/loader.rb:192:in `block in configure_vagrant'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/config/v2/loader.rb:37:in `load'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/config/loader.rb:126:in `block (2 levels) in load'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/config/loader.rb:119:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/config/loader.rb:119:in `block in load'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/config/loader.rb:116:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/config/loader.rb:116:in `load'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/vagrantfile.rb:29:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/environment.rb:793:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/environment.rb:793:in `vagrantfile'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/environment.rb:178:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/bin/vagrant:144:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/bin/vagrant:144:in `<main>'
Administrator@CBS85CFXNI4FWJ5 /cygdrive/f/teracy/iorad-dev
$```

**Comment by datphan** [comment]
maybe the latest version of vagrant (2.2.0) cause this, pls try the older one (2.1.2) to see if it is working:
https://releases.hashicorp.com/vagrant/

https://github.com/hashicorp/vagrant/issues/10303#issuecomment-431170734

**Comment by datphan** [comment]
Seem it is working with the downgrade, @hoavt can you confirm

**Comment by hoavt** [comment]
```Administrator@CBS85CFXNI4FWJ5 /cygdrive/f/teracy/iorad-dev
$ vagrant status
[TeracyDev::Util][WARN]: The _id: '0' is deprecated, use the _id: 'kernel-core' instead for {"_id"=>"0", "location"=>{"git"=>{"remote"=>{"origin"=>"https://github.com/teracyhq-incubator/teracy-dev-core.git"}, "branch"=>"develop"}}, "require_version"=>">= 0.4.0-SNAPSHOT"}

[TeracyDev::Plugin][INFO]: installing plugin: {"_id"=>"essential-0", "name"=>"vagrant-hostmanager", "version"=>"", "state"=>"installed", "config_key"=>"hostmanager", "enabled"=>true, "options"=>{"enabled"=>true, "manage_host"=>true, "manage_guest"=>true}, "sources"=>["https://rubygems.org/", "https://gems.hashicorp.com/"]}

[TeracyDev::Plugin][INFO]: installing plugin: {"_id"=>"essential-0", "name"=>"vagrant-hostmanager", "version"=>"", "state"=>"installed", "config_key"=>"hostmanager", "enabled"=>true, "options"=>{"enabled"=>true, "manage_host"=>true, "manage_guest"=>true}, "sources"=>["https://rubygems.org/", "https://gems.hashicorp.com/"]}

C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:185:in `encode!': code converter not found (UTF-16LE to Windows-1258) (Encoding::ConverterNotFoundError)
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:185:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:250:in `exception'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:250:in `raise'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:250:in `check'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:320:in `QueryValue'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:644:in `read'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/resolv.rb:67:in `read_s'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/resolv.rb:101:in `block in get_info'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:435:in `open'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/registry.rb:542:in `open'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/resolv.rb:91:in `get_info'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/win32/resolv.rb:21:in `get_resolv_info'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:1002:in `default_config_hash'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:1019:in `block in lazy_initialize'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:1012:in `synchronize'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:1012:in `lazy_initialize'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:358:in `block in lazy_initialize'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:356:in `synchronize'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:356:in `lazy_initialize'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:516:in `fetch_resource'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:510:in `each_resource'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/resolv.rb:491:in `getresource'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/remote_fetcher.rb:105:in `api_endpoint'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/source.rb:47:in `api_uri'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/source.rb:183:in `load_specs'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/bundler.rb:360:in `block in validate_configured_sources!'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/source_list.rb:98:in `each'
        from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.4.0/rubygems/source_list.rb:98:in `each_source'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/bundler.rb:358:in `validate_configured_sources!'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/bundler.rb:285:in `internal_install'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/bundler.rb:106:in `install'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/plugin/manager.rb:62:in `block in install_plugin'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/plugin/manager.rb:72:in `install_plugin'
        from F:/teracy/iorad-dev/lib/teracy-dev/plugin.rb:36:in `block in sync'
        from F:/teracy/iorad-dev/lib/teracy-dev/plugin.rb:16:in `each'
        from F:/teracy/iorad-dev/lib/teracy-dev/plugin.rb:16:in `sync'
        from F:/teracy/iorad-dev/extensions/teracy-dev-core/lib/teracy-dev-core/config/plugins.rb:17:in `configure'
        from F:/teracy/iorad-dev/lib/teracy-dev/config/manager.rb:40:in `block in configure'
        from F:/teracy/iorad-dev/lib/teracy-dev/config/manager.rb:38:in `each'
        from F:/teracy/iorad-dev/lib/teracy-dev/config/manager.rb:38:in `configure'
        from F:/teracy/iorad-dev/lib/teracy-dev/loader.rb:185:in `configure'
        from F:/teracy/iorad-dev/lib/teracy-dev/loader.rb:192:in `block in configure_vagrant'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/config/v2/loader.rb:37:in `load'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/config/loader.rb:126:in `block (2 levels) in load'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/config/loader.rb:119:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/config/loader.rb:119:in `block in load'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/config/loader.rb:116:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/config/loader.rb:116:in `load'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/vagrantfile.rb:28:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/environment.rb:777:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/environment.rb:777:in `vagrantfile'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/environment.rb:523:in `host'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/environment.rb:191:in `block in action_runner'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/action/runner.rb:33:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/environment.rb:510:in `hook'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/lib/vagrant/environment.rb:759:in `unload'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:164:in `ensure in <main>'
        from C:/HashiCorp/Vagrant/embedded/gems/2.1.2/gems/vagrant-2.1.2/bin/vagrant:164:in `<main>'

Administrator@CBS85CFXNI4FWJ5 /cygdrive/f/teracy/iorad-dev
$ vagrant --version
Vagrant 2.1.2

Administrator@CBS85CFXNI4FWJ5 /cygdrive/f/teracy/iorad-dev``

@datphan vagrant is still not working with vagrant 2.1.2

**Comment by datphan** [comment]
this bug maybe is only happen to win 7, and the solution is to set region to US:

   Control Pane > Region >
     > Location > Home Location > United States
     > Administrative > Change system locale… > Chose English (United States) > Apply

**Comment by hoatle** [comment]
so this is not really a bug to teracy-dev but vagrant, we need to update docs for this case.

assigned to @hoavt

**Comment by hoatle** [comment]
phuonglm8:52 AM
99% la do system locale
￼￼￼￼￼
8:52 AM
restart xong check lại nhé
8:55 AM
http://maytinhadongjsc.com/1-thu-thuat-tin-tuc/135-huong-dan-khac-phuc-loi-utf-16le-to-windows-1258.html

phuonglm [9:01 AM]
cái doc của mình cũng nên ghi là chỉ support windows 7 SP1 x64 trở lên
SP1 còn chứ sao bỏ được nhỉ
ghi chung chung windows 7 8 10 user dùng bản 32 bit là bị lỗi
