### ISSUE TITLE
failed to uninstall plugins

### ISSUE THREAD

**Issue by hoatle** [teracyhq/dev#575]
```
$ vagrant status
[TeracyDev::Plugin][INFO]: uninstalling plugin: {"_id"=>"entry-gatling-rsync", "name"=>"vagrant-gatling-rsync", "version"=>"", "state"=>"uninstalled", "enabled"=>true, "config_key"=>"gatling", "options"=>{"latency"=>0.5, "time_format"=>"%H:%M:%S", "rsync_on_startup"=>true}}

/opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/bundler.rb:219:in `realpath': No such file or directory @ realpath_rec - /Users/hoatle/teracy-dev/.vagrant/plugins (Errno::ENOENT)
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/bundler.rb:219:in `realpath'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/bundler.rb:219:in `block in clean'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/bundler.rb:218:in `delete_if'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/bundler.rb:218:in `clean'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/plugin/manager.rb:200:in `uninstall_plugin'
	from /Users/hoatle/teracy-dev/lib/teracy-dev/plugin.rb:42:in `block in sync'
	from /Users/hoatle/teracy-dev/lib/teracy-dev/plugin.rb:16:in `each'
	from /Users/hoatle/teracy-dev/lib/teracy-dev/plugin.rb:16:in `sync'
	from /Users/hoatle/teracy-dev/extensions/teracy-dev-core/lib/teracy-dev-core/config/plugins.rb:17:in `configure'
	from /Users/hoatle/teracy-dev/lib/teracy-dev/config/manager.rb:40:in `block in configure'
	from /Users/hoatle/teracy-dev/lib/teracy-dev/config/manager.rb:38:in `each'
	from /Users/hoatle/teracy-dev/lib/teracy-dev/config/manager.rb:38:in `configure'
	from /Users/hoatle/teracy-dev/lib/teracy-dev/loader.rb:193:in `configure'
	from /Users/hoatle/teracy-dev/lib/teracy-dev/loader.rb:199:in `block in configure_vagrant'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/config/v2/loader.rb:37:in `load'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/config/loader.rb:126:in `block (2 levels) in load'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/config/loader.rb:119:in `each'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/config/loader.rb:119:in `block in load'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/config/loader.rb:116:in `each'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/config/loader.rb:116:in `load'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/vagrantfile.rb:29:in `initialize'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/environment.rb:793:in `new'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/environment.rb:793:in `vagrantfile'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/lib/vagrant/environment.rb:178:in `initialize'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/bin/vagrant:144:in `new'
	from /opt/vagrant/embedded/gems/2.2.0/gems/vagrant-2.2.0/bin/vagrant:144:in `<main>'
```

**Comment by hoatle** [comment]
- we should add support for the `env_local: false` config (global scope by default)

- installation/uninstallation should support both local and global scope.

- update system.yaml to require vagrant >= 2.1.3 (env_local was introduced since vagrant 2.1.3)

**Comment by hieptranquoc** [comment]
Since vagrant 2.1.3, all plugin behavior after vagrant being loaded will be interpreted as local plugin! Therefore we will no longer be able to install/uninstall the plugin automatically! This is identified as a vagrant error when providing API. 
Workaround:
- should install/ uninstall as local plugin! 
- use the vagrant command to manage plugins.
